export const NOTIFICATION_TYPES = {
  ALERT: 'ALERT',
  REMINDER: 'REMINDER',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  MESSAGE: 'MESSAGE',
  SYSTEM: 'SYSTEM',
  WARNING: 'WARNING',
  INFO: 'INFO'
};

export const NOTIFICATION_TYPE_LABELS = {
  [NOTIFICATION_TYPES.ALERT]: 'Alert',
  [NOTIFICATION_TYPES.REMINDER]: 'Reminder',
  [NOTIFICATION_TYPES.ANNOUNCEMENT]: 'Announcement',
  [NOTIFICATION_TYPES.MESSAGE]: 'Message',
  [NOTIFICATION_TYPES.SYSTEM]: 'System',
  [NOTIFICATION_TYPES.WARNING]: 'Warning',
  [NOTIFICATION_TYPES.INFO]: 'Information'
};

export const NOTIFICATION_TYPE_ICONS = {
  [NOTIFICATION_TYPES.ALERT]: '⚠️',
  [NOTIFICATION_TYPES.REMINDER]: '🔔',
  [NOTIFICATION_TYPES.ANNOUNCEMENT]: '📢',
  [NOTIFICATION_TYPES.MESSAGE]: '💬',
  [NOTIFICATION_TYPES.SYSTEM]: '⚙️',
  [NOTIFICATION_TYPES.WARNING]: '🚨',
  [NOTIFICATION_TYPES.INFO]: 'ℹ️'
};

export const NOTIFICATION_TYPE_COLORS = {
  [NOTIFICATION_TYPES.ALERT]: '#ff6b6b',
  [NOTIFICATION_TYPES.REMINDER]: '#4ecdc4',
  [NOTIFICATION_TYPES.ANNOUNCEMENT]: '#45b7d1',
  [NOTIFICATION_TYPES.MESSAGE]: '#96ceb4',
  [NOTIFICATION_TYPES.SYSTEM]: '#5d6d7e',
  [NOTIFICATION_TYPES.WARNING]: '#feca57',
  [NOTIFICATION_TYPES.INFO]: '#54a0ff'
};