//src/modules/examination/constants/gradeScales.js
export const DEFAULT_GRADE_SCALES = {
  STANDARD_100: {
    id: 1,
    name: "Standard 100-Point Scale",
    system: "percentage",
    passingPercentage: 40,
    thresholds: [
      { min: 97, max: 100, grade: "A+", gpa: 4.0, description: "Outstanding" },
      { min: 93, max: 96.9, grade: "A", gpa: 4.0, description: "Excellent" },
      { min: 90, max: 92.9, grade: "A-", gpa: 3.7, description: "Very Good" },
      { min: 87, max: 89.9, grade: "B+", gpa: 3.3, description: "Good Plus" },
      { min: 83, max: 86.9, grade: "B", gpa: 3.0, description: "Good" },
      {
        min: 80,
        max: 82.9,
        grade: "B-",
        gpa: 2.7,
        description: "Satisfactory Plus",
      },
      {
        min: 77,
        max: 79.9,
        grade: "C+",
        gpa: 2.3,
        description: "Satisfactory",
      },
      { min: 73, max: 76.9, grade: "C", gpa: 2.0, description: "Average" },
      {
        min: 70,
        max: 72.9,
        grade: "C-",
        gpa: 1.7,
        description: "Below Average",
      },
      { min: 60, max: 69.9, grade: "D", gpa: 1.0, description: "Poor" },
      { min: 0, max: 59.9, grade: "F", gpa: 0.0, description: "Fail" },
    ],
  },
  LETTER_GRADE: {
    id: 2,
    name: "Letter Grade System",
    system: "letter",
    passingGrade: "D",
    thresholds: [
      { grade: "A+", description: "Outstanding", points: 4.0 },
      { grade: "A", description: "Excellent", points: 4.0 },
      { grade: "A-", description: "Very Good", points: 3.7 },
      { grade: "B+", description: "Good Plus", points: 3.3 },
      { grade: "B", description: "Good", points: 3.0 },
      { grade: "B-", description: "Satisfactory Plus", points: 2.7 },
      { grade: "C+", description: "Satisfactory", points: 2.3 },
      { grade: "C", description: "Average", points: 2.0 },
      { grade: "C-", description: "Below Average", points: 1.7 },
      { grade: "D", description: "Poor", points: 1.0 },
      { grade: "F", description: "Fail", points: 0.0 },
    ],
  },
};

export const GRADE_COLORS = {
  "A+": "#10b981",
  A: "#10b981",
  "A-": "#10b981",
  "B+": "#3b82f6",
  B: "#3b82f6",
  "B-": "#3b82f6",
  "C+": "#f59e0b",
  C: "#f59e0b",
  "C-": "#f59e0b",
  D: "#ef4444",
  F: "#dc2626",
};
