// src/modules/budget/enums/budget.enum.ts
export enum BudgetCategory {
  SALARIES = 'SALARIES',
  OPERATIONAL = 'OPERATIONAL',
  CAPITAL = 'CAPITAL',
  REVENUE = 'REVENUE',
  RESEARCH = 'RESEARCH',
  DEVELOPMENT = 'DEVELOPMENT',
  MAINTENANCE = 'MAINTENANCE',
  UTILITIES = 'UTILITIES',
  TRAINING = 'TRAINING',
  TECHNOLOGY = 'TECHNOLOGY',
  STUDENT_WELFARE = 'STUDENT_WELFARE',
  SPORTS = 'SPORTS',
  LIBRARY = 'LIBRARY',
  ADMINISTRATION = 'ADMINISTRATION',
}

export enum BudgetType {
  ANNUAL = 'ANNUAL',
  QUARTERLY = 'QUARTERLY',
  PROJECT_BASED = 'PROJECT_BASED',
}

export enum BudgetStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  FROZEN = 'FROZEN',
}

export enum TransferStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXECUTED = 'EXECUTED',
}

export enum CommitmentStatus {
  ACTIVE = 'ACTIVE',
  REALIZED = 'REALIZED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum AlertType {
  SOFT_STOP = 'SOFT_STOP',
  HARD_STOP = 'HARD_STOP',
  FORECAST_OVERRUN = 'FORECAST_OVERRUN',
}