export enum UserRole { 
SUPER_ADMIN = 'SUPER_ADMIN', 
ADMIN = 'ADMIN', 
TEACHER = 'TEACHER', 
STUDENT = 'STUDENT', 
PARENT = 'PARENT', 
ACCOUNTANT = 'ACCOUNTANT', 
LIBRARIAN = 'LIBRARIAN', 
HR_MANAGER = 'HR_MANAGER', 
} 


